apiVersion: v1
kind: Service
metadata:
  name: {{ include "domain-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "domain-exporter.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "domain-exporter.selectorLabels" . | nindent 4 }}
  ports:
    - port: 9203
      targetPort: http
      protocol: TCP
      name: http
