dashboards:
  targetFolder: "domains"

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: localhost
      paths:
        - path: "/domain-exporter(/|$)(.*)"
          pathType: Prefix

domains:
  - google.com
  - habr.ru
  - github.com
  - tut.by
  - cnn.com
  - gitignore.io
  - gosuslugi.ru
  - vaikutis.lt
  - reddit.com
  - amazon.pl
  - amazon.com
  - olx.ua
  - ok.ru
  - censor.net
  - mail.ru
  - aliexpress.ru
  - domain-is-not-found.net
