apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-scraper.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    # jobLabel: node-exporter
    {{- include "node-scraper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "node-scraper.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: metrics
