name: Run Helm Test Cases
on: [push]
jobs:
  Helm-Template:
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: sh ${{ github.workspace }}/tests/template-all/run.sh
  Helm-Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint Helm
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm lint ${{ github.workspace }}/.helm/
