name: Run Helm Test Cases
on: [push]
jobs:
  Helm-Template:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}/tests/template-all
      - name: Run Tests
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: ${{ github.workspace }}/tests/template-all/run.sh
  Helm-Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}/.helm/
      - name: Lint Helm
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm lint ${{ github.workspace }}/.helm/
